### ISSUE TITLE
Missing last list item

### ISSUE THREAD

**Issue by DoctorMcKay** [Maximillion195/google-shopping-list#2]
Firstly, thanks so much for making this! It's a real shame Google doesn't have some kind of API for this.

I noticed that when using this module, the last item on the list was missing. I commented out [this line](https://github.com/Maximillion195/google-shopping-list/blob/master/index.js#L78) and my entire list started being returned. Maybe Google changed something?

**Comment by Maximillion195** [comment]
Hey @DoctorMcKay,

Thanks for raising this. I was removing the 'is checked off' from the array. Obviously this isn't always there if nothing has been checked off the list.

![image](https://user-images.githubusercontent.com/9414699/59206636-47aa9a00-8b9d-11e9-84fd-33c9ebdbfe71.png)

I will add a check for it and only remove it if it is present.

**Comment by Maximillion195** [comment]
Sorry for the delay, added a quick fix to solve this.

**Comment by DoctorMcKay** [comment]
:+1: Thanks!
